### ISSUE TITLE
Consider adding SophyCore to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [FarDragi/SophyCore#1]
Hey @Gabriel-Paulucci, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by Gabriel-Paulucci** [comment]
hello, I don't know if you remember me, thanks for the PR, I'll fix my readme, and send it to showcase, I believe I'll send it by tomorrow

**Comment by billy1624** [comment]
Hey @Gabriel-Paulucci, nice to be chatting with you again! Again, thanks for the contributions in SeaORM :P

**Comment by billy1624** [comment]
Please :) hahaa
